config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to => "home#index"
  resources :todo

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if user_signed_in?
      redirect_to :controller => 'todo', :action => 'index'
  end

end

app/controllers/todo_controller.rb
class TodoController < ApplicationController
  def index
    @todos = Todo.where(done: false)
    @todone = Todo.where(done: true)
  end

  def new
    @todo = Todo.new
  end

  def todo_params
    params.require(:todo).permit(:name, :done)
  end

  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to todo_index_path, :notice => "Your todo task is added!"
    else
      render "new"
    end
  end

  def update
    @todo = Todo.find(params[:id])

    if @todo.update_attribute(:done, true)
      redirect_to todo_index_path, :notice => "Your todo task is marked as done!"
    else
      redirect_to todo_index_path, :notice => "Your todo task is not marked as done!"

    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    redirect_to todo_index_path, :notice => "Your todo task is deleted!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/views/home/index.html.haml
%h1 To-Do Website

%h2 To-Do:

- @todos.each do |t|
  %p
    %strong= t.name
    %small= link_to "Mark as Done", todo_path(t), :method => :put

%h2 Done:
- @todone.each do |t|
  %p
    %strong= t.name
    %small= link_to "Remove", t, :confirm => "Are you sure?", :method => :delete


%p= link_to "Add a to-do task", new_todo_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
    You are currently signed in as <%= current_user.email %>, not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
<% end %>

<% flash.each do |name, message| %>
    <%= content_tag :div, message, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/todo/index.html.haml
%h1 To-Do Website

%h2 To-Do:

- @todos.each do |t|
  %p
    = t.name
    %small= link_to "Mark as Done", todo_path(t), :method => :put

%h2 Done:
- @todone.each do |t|
  %p
    = t.name
    %small= link_to "Remove", t, :confirm => "Are you sure?", :method => :delete


%p= link_to "Add a to-do task", new_todo_path

app/views/todo/new.html.haml
%h1 Add new todo tasks

= form_for @todo, :url => todo_index_path(@todo) do |f|
  = f.label :name
  = f.text_field :name
  = f.hidden_field :done, :value => false
  = f.submit "Add"